title: Aniekan Jr - Computer Systems Engineer
baseurl: "/"
social:
  name: Aniekan Jr
  links:
    - title: GitHub
      url: https://github.com/aniekanbane
    - title: LinkedIn
      url: https://linkedin.com/in/aniekanjr

exclude:
  - README.md